package mp3CategorizationServer;

import java.util.HashMap;
import java.util.Map;

public class GenreMapper {

	public static Map<Integer, String> types = new HashMap<>();
	static {
		types.put(0,"Blues");
		types.put(1,"Classic Rock");
		types.put(2,"Country");
		types.put(3,"Dance");
		types.put(4,"Disco");
		types.put(5,"Funk");
		types.put(6,"Grunge");
		types.put(7,"Hip-Hop");
		types.put(8,"Jazz");
		types.put(9,"Metal");
		types.put(10,"New Age");
		types.put(11,"Oldies");
		types.put(12,"Other");
		types.put(13,"Pop");
		types.put(14,"R&B");
		types.put(15,"Rap");
		types.put(16,"Reggae");
		types.put(17,"Rock");
		types.put(18,"Techno");
		types.put(19,"Industrial");
		types.put(20,"Alternative");
		types.put(21,"Ska");
		types.put(22,"Death Metal");
		types.put(23,"Pranks");
		types.put(24,"Soundtrack");
		types.put(25,"Euro-Techno");
		types.put(26,"Ambient");
		types.put(27,"Trip-Hop");
		types.put(28,"Vocal");
		types.put(29,"Jazz+Funk");
		types.put(30,"Fusion");
		types.put(31,"Trance");
		types.put(32,"Classical");
		types.put(33,"Instrumental");
		types.put(34,"Acid");
		types.put(35,"House");
		types.put(36,"Game");
		types.put(37,"Sound Clip");
		types.put(38,"Gospel");
		types.put(39,"Noise");
		types.put(40,"Alt. Rock");
		types.put(41,"Bass");
		types.put(42,"Soul");
		types.put(43,"Punk");
		types.put(44,"Space");
		types.put(45,"Meditative");
		types.put(46,"Instrumental Pop");
		types.put(47,"Instrumental Rock");
		types.put(48,"Ethnic");
		types.put(49,"Gothic");
		types.put(50,"Darkwave");
		types.put(51,"Techno-Industrial");
		types.put(52,"Electronic");
		types.put(53,"Pop-Folk");
		types.put(54,"Eurodance");
		types.put(55,"Dream");
		types.put(56,"Southern Rock");
		types.put(57,"Comedy");
		types.put(58,"Cult");
		types.put(59,"Gangsta Rap");
		types.put(60,"Top 40");
		types.put(61,"Christian Rap");
		types.put(62,"Pop/Funk");
		types.put(63,"Jungle");
		types.put(64,"Native American");
		types.put(65,"Cabaret");
		types.put(66,"New Wave");
		types.put(67,"Psychedelic");
		types.put(68,"Rave");
		types.put(69,"Showtunes");
		types.put(70,"Trailer");
		types.put(71,"Lo-Fi");
		types.put(72,"Tribal");
		types.put(73,"Acid Punk");
		types.put(74,"Acid Jazz");
		types.put(75,"Polka");
		types.put(76,"Retro");
		types.put(77,"Musical");
		types.put(78,"Rock & Roll");
		types.put(79,"Hard Rock");
		types.put(80,"Folk");
		types.put(81,"Folk-Rock");
		types.put(82,"National Folk");
		types.put(83,"Swing");
		types.put(84,"Fast-Fusion");
		types.put(85,"Bebop");
		types.put(86,"Latin");
		types.put(87,"Revival");
		types.put(88,"Celtic");
		types.put(89,"Bluegrass");
		types.put(90,"Avantgarde");
		types.put(91,"Gothic Rock");
		types.put(92,"Progressive Rock");
		types.put(93,"Psychedelic Rock");
		types.put(94,"Symphonic Rock");
		types.put(95,"Slow Rock");
		types.put(96,"Big Band");
		types.put(97,"Chorus");
		types.put(98,"Easy Listening");
		types.put(99,"Acoustic");
		types.put(100,"Humour");
		types.put(101,"Speech");
		types.put(102,"Chanson");
		types.put(103,"Opera");
		types.put(104,"Chamber Music");
		types.put(105,"Sonata");
		types.put(106,"Symphony");
		types.put(107,"Booty Bass");
		types.put(108,"Primus");
		types.put(109,"Porn Groove");
		types.put(110,"Satire");
		types.put(111,"Slow Jam");
		types.put(112,"Club");
		types.put(113,"Tango");
		types.put(114,"Samba");
		types.put(115,"Folklore");
		types.put(116,"Ballad");
		types.put(117,"Power Ballad");
		types.put(118,"Rhythmic Soul");
		types.put(119,"Freestyle");
		types.put(120,"Duet");
		types.put(121,"Punk Rock");
		types.put(122,"Drum Solo");
		types.put(123,"A Cappella");
		types.put(124,"Euro-House");
		types.put(125,"Dance Hall");
		types.put(126,"Goa");
		types.put(127,"Drum & Bass");
		types.put(128,"Club-House");
		types.put(129,"Hardcore");
		types.put(130,"Terror");
		types.put(131,"Indie");
		types.put(132,"BritPop");
		types.put(133,"Afro-Punk");
		types.put(134,"Polsk Punk");
		types.put(135,"Beat");
		types.put(136,"Christian Gangsta Rap");
		types.put(137,"Heavy Metal");
		types.put(138,"Black Metal");
		types.put(139,"Crossover");
		types.put(140,"Contemporary Christian");
		types.put(141,"Christian Rock");
		types.put(142,"Merengue");
		types.put(143,"Salsa");
		types.put(144,"Thrash Metal");
		types.put(145,"Anime");
		types.put(146,"JPop");
		types.put(147,"Synthpop");
		types.put(148,"Abstract");
		types.put(149,"Art Rock");
		types.put(150,"Baroque");
		types.put(151,"Bhangra");
		types.put(152,"Big Beat");
		types.put(153,"Breakbeat");
		types.put(154,"Chillout");
		types.put(155,"Downtempo");
		types.put(156,"Dub");
		types.put(157,"EBM");
		types.put(158,"Eclectic");
		types.put(159,"Electro");
		types.put(160,"Electroclash");
		types.put(161,"Emo");
		types.put(162,"Experimental");
		types.put(163,"Garage");
		types.put(164,"Global");
		types.put(165,"IDM");
		types.put(166,"Illbient");
		types.put(167,"Industro-Goth");
		types.put(168,"Jam Band");
		types.put(169,"Krautrock");
		types.put(170,"Leftfield");
		types.put(171,"Lounge");
		types.put(172,"Math Rock");
		types.put(173,"New Romantic");
		types.put(174,"Nu-Breakz");
		types.put(175,"Post-Punk");
		types.put(176,"Post-Rock");
		types.put(177,"Psytrance");
		types.put(178,"Shoegaze");
		types.put(179,"Space Rock");
		types.put(180,"Trop Rock");
		types.put(181,"World Music");
		types.put(182,"Neoclassical");
		types.put(183,"Audiobook");
		types.put(184,"Audio Theatre");
		types.put(185,"Neue Deutsche Welle");
		types.put(186,"Podcast");
		types.put(187,"Indie Rock");
		types.put(188,"G-Funk");
		types.put(189,"Dubstep");
		types.put(190,"Garage Rock");
		types.put(191,"Psybient");
	}
}